### ISSUE TITLE
Notice: Undefined index: id in /home/laneross/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

### ISSUE THREAD

**Issue by studioserviziweb** [mageplaza/magento-2-email-attachments#11]
How to resolve this problem?

Magento V2.3 - Extension Email Attachments

Thank You

**Comment by daniel100097** [comment]
@studioserviziweb see https://github.com/mageplaza/magento-2-email-attachments/pull/14
