### ISSUE TITLE
Not working with Magento 2.3.3

### ISSUE THREAD

**Issue by candreas-isp** [mageplaza/magento-2-email-attachments#12]
When trying to use this extension with Magento 2.3.3 I get the following error message each time I try to send an order email from the store with an attachment:
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mageplaza\EmailAttachments\Model\MailEvent::dispatch() must be an instance of Mageplaza\EmailAttachments\Mail\Message, instance of Magento\Framework\Mail\EmailMessage given, called in /var/www/html/xxxxx/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php on line 64 and defined in /var/www/html/xxxxx/vendor/mageplaza/module-email-attachments/Model/MailEvent.php:102

The module is running with Magento 2.3.2 without any problems.

**Comment by Condelab** [comment]
same here
 
Fatal error: Uncaught TypeError: Argument 1 passed to Mageplaza\EmailAttachments\Model\MailEvent::dispatch() must be an instance of Mageplaza\EmailAttachments\Mail\Message, instance of Magento\Framework\Mail\EmailMessage given, called in /var/www/html/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php on line 64 and defined in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php:102 Stack trace: #0 /var/www/html/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php(64): Mageplaza\EmailAttachments\Model\MailEvent->dispatch(Object(Magento\Framework\Mail\EmailMessage)) #1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\EmailAttachments\Mail\TransportFactory->aroundCreate(Object(Magento\Framework\Mail\TransportInterfaceFactory\Interceptor), Object(Closure), Array) #2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Mail\TransportInterfaceFactory\Interceptor->Magento\Framework\Interception\{closu in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php on line 102

**Comment by candreas-isp** [comment]
After installing the "EmailMessageInterface_2.3.3_backward_compatibility_composer" patch from the Magento website this error disappeared, but unfortunately now there is another one:
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Mail\EmailMessage::createAttachment() in /var/www/html/xxxxxx/vendor/mageplaza/module-email-attachments/Model/MailEvent.php:165

**Comment by juules** [comment]
I have the same problem. 
When can we expect an update?

**Comment by ananth-iyer** [comment]
You read more about the issue here: https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-3-open-source.html#backward-incompatible-changes

**Comment by mageprashant** [comment]
I have the same issue in Magento 2.3.3 so any update for the issue?

**Comment by miketechtwo** [comment]
Hi Mageplaza,

When can we expect an update about this issue since this module is not working on Magento 2.3.3?

**Comment by NicoSiebler** [comment]
An update would be much appreciated. Also some hints how to use a workaround manually.
The EmailMessageInterface_2.3.3_backward_compatibility_composer patch from Magento does not help with the current version of the module.

**Comment by miketechtwo** [comment]
As a quick fix you can use the develop version of the module:

`composer require mageplaza/module-email-attachments:dev-develop`

**Comment by NicoSiebler** [comment]
@miketechtwo 
Thanks!
We still had to do a small change due to the eMailInterface patch:

In Mail/Message.php
from

`    private $zendMessage;`

to

`    protected $zendMessage;`

Otherwise code compilation would fail with a fatal error.

> PHP message: PHP Fatal error:  Access level to Mageplaza\\EmailAttachments\\Mail\\Message::$zendMessage must be protected (as in class Magento\\Framework\\Mail\\Message) or weaker in .. /vendor/mageplaza/module-email-attachments/Mail/Message.php on line 34

**Comment by datvm231** [comment]
Hello everyone,

Sorry for the delayed response. We have updated the extension to compatible with Magento 2.3.3 recently. It is available in develop branch at the moment.
