### ISSUE TITLE
Magento 2.3.4 order confirmation not sending anymore

### ISSUE THREAD

**Issue by Kroellie** [mageplaza/magento-2-email-attachments#15]
Hi,

Your plugin causes the order confirmation mail not being sent anymore. When I disable your plugin, it sends again. Magento 2.3.4 has some serious email issues by itself, not sure if this is related. Had to patch the core files of magento to even get it to send email. I patched with:

https://github.com/magento/magento2/commit/6976aabdfdab91a9d06e412c2ed619538ed034b6

But then, after installing your plugin, there is suddenly an extra attachment AT00001.htm as well as PDF to my invoice email.

Also I noticed the order confirmation mail not being sent anymore.

**Comment by Shinichi69** [comment]
Hi @Kroellie 

Please install our Smtp extension to support sending emails:
- https://github.com/mageplaza/magento-2-smtp
Then please check again and let me know the result.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
