### ISSUE TITLE
Email Not Recieve to Customer.

### ISSUE THREAD

**Issue by stenovishal98** [mageplaza/magento-2-email-attachments#16]
The problem is coming in this module when I enable this model, the email  not receiving to Customer. If I checked the error log of smtp, then that error is visible. When he is resend from me the email is going.

**Comment by thaimageplaza** [comment]
Can you send me the error message shown in SMTP?
Besides, I’m not sure that I can understand your issue/question, 
so could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?
I really hope for your cooperation. Thank you!

**Comment by stenovishal98** [comment]
I found the Solution. And problem solved.
