### ISSUE TITLE
Invoice PDF not attached with order email

### ISSUE THREAD

**Issue by samnantham** [mageplaza/magento-2-email-attachments#17]
After installed this plugin and made all the necessary settings in admin side. But when create order from store email received without invoice pdf.

**Comment by Shinichi69** [comment]
Hi @samnantham 

I’m Shin from Mageplaza and I will support you on this issue.

When you create an order, there will be no pdf attached.
You need to create an invoice for that order and when the email is sent it will attach a pdf invoice.
- https://prnt.sc/sgfeh2

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
