### ISSUE TITLE
Body and attachments get duplicated in next email

### ISSUE THREAD

**Issue by MedvidDV** [mageplaza/magento-2-email-attachments#20]
magento 2.3.4.
configuration: Attach PDF file for: Invoice
Attach Terms and Conditions to: Order

We have a configuration like this: send terms and conditions in Order email and generated invoice in Invoice email.
when customer uses gateway like Paypal with immediate capture, emails get sent one by one withing couple seconds. Order email is ok, the Invoice email (the next one) repeats the body of the previous email + insert its own, same with attachments

Expected result: email bodies and attachments are separated from each other

Actual result: sequence emails repeat body and attachments from the previous ones

**Comment by Shinichi69** [comment]
Hi @MedvidDV 

I checked your problem on my local and I cannot reproduce your problem.

To facilitate your support of this issue.
Please create an internal ticket here and I will assist you:
- https://mageplaza.freshdesk.com/support/tickets/new
Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.

**Comment by smagdziarz** [comment]
We've also noticed the same behavior after upgrading an older version (1.0.2) of the module to a more current one (1.0.5, 1.0.6). We have a script sending shipment confirmation emails in a loop, and the email body parts keep stacking. So the first email is OK, but the second email has the first content as well as the second etc.

From what I've been able to see is that the call to `$this->setBodyAttachment($message);` in Model/MailEvent.php causes this duplicate content. After this call, the `$message->getBody()->getParts()` has more than one part.

**Comment by websharp** [comment]
Hi, MailEvent.php does not clean up its private attribute `parts`, which results using this class by DI and Singleton and running through a stack of mails without isolated request, the stack array is just growing.

My solution for this in `Model/MailEvent.php` to add in line 261 (last line of the private function `setBodyAttachment`) `$this->parts = [];`  for cleanup. Maybe there is a better place in the class.
