### ISSUE TITLE
order confirmation empty but with content as attachment

### ISSUE THREAD

**Issue by maschwa88** [mageplaza/magento-2-email-attachments#22]
Hello together,

i have a problem with this plugin and Magento 2.3.5. The invoice Email is working fine with PDF attachment. But the order confirmation email which was a "normal html" Email before  now is empty and the content is packed in an attachment.html

any idea how i can change that? is that a intended "feature" ?

Greetings,
Marc

**Comment by Shinichi69** [comment]
Hi @maschwa88,

I checked your problem with Magento 2.3.5.
However, I cannot reproduce your problem. The extension is still working fine.

Please provide me with the settings screenshots in the extension's config and steps to reproduce your problem.

Thanks so much!

**Comment by maschwa88** [comment]
Dear Shinichi69,

thank you very much for your response. Indeed the problem ist not in mageplaza plugin. meanwhile i found that the problem seems to occur in thunderbird from version >= 68 and is caused from the file headers.php in vendor/laminas/laminas-mail/src.

if i make following changes than it works:

$current = $headers;
        // $current->setEncoding($encoding);
        // patch
        $current->setEncoding($key === 'contentdisposition' && $current->getFieldValue(false) === 'inline' ? 'ASCII' : $encoding);

        $this->headers[$index] = $current;
        return $current;

Greetings,
Marc
