### ISSUE TITLE
Not Attaching PDF as per store view

### ISSUE THREAD

**Issue by RonakParmar** [mageplaza/magento-2-email-attachments#23]
Hello There,
Thank you for this awesome module providing at free of cost. I am using it in one of my projects and found this module is attaching invoice pdf in default store view language. It should convert the invoice pdf based on store view language. 
Can you please let me know is it possible to translate the invoice pdf attach it in email? 
For Example: I have one website having two store view English and Arabic. English is my default store view and If I am placing an order from Arabic store view then the email is in Arabic language but the PDF is in English language because english is my default store view. Is it possible to attach Arabic invoice pdf in Arabic invoice email ? 

Thank you.

**Comment by Shinichi69** [comment]
Hi @RonakParmar 

Our extensions are getting the PDF invoice file under Magento's default template.
So if you want to change the language in the template, you will need to add a translated file according to the language in your Arabic store view.

Please add the translate CSV file with the language you need into the directory under the path:
- vendor\magento\module-sales\i18n

Here is an example when I want to translate emails to Vietnamese.
- https://prnt.sc/up2rga

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.

**Comment by RonakParmar** [comment]
@Shinichi69 Thank you for the reply, In my case email content is getting translated in Arabic language but the attached PDF is not getting translated in Arabic, the PDF content is in english language. This is the issue. 
Please provide any solution for this.

Thank you.

**Comment by RonakParmar** [comment]
@Shinichi69  Can you please look into this issue? Still having same issue.
