### ISSUE TITLE
Confirmation-mail of wrong customer/s is/are attached to the proper one

### ISSUE THREAD

**Issue by berwa** [mageplaza/magento-2-email-attachments#26]
Hello Mageplaza-team,
one of our shop-operators reported that _sometimes_ order-confirmation emails of one or more other customers are added as an attachment to the proper order-confirmation email.
Additionally the configured PDF-attachment is added multiple times to those emails.
The first part is especially critical as this might publish personal data of one shop-customer to another one (GDPR-violation, ...).

We could reproduce the issue in a plain Magento-installation and trace down the _sometimes_-part to cases where multiple orders are placed within the same minute (_Asynchronous sending_ of emails enabled in Magento configuration, Magento cronjob being executed once every minute).

Best regards

### Preconditions (*)
1. Magento 2.3.5-p2 Commerce installation (also reproducible in plain installation with sample data)
2. _Asynchronous sending_ enabled in Magento configuration (_Sales > Sales Emails > General settings_)
3. Module-version 1.0.5 or 1.0.6 installed
4. Module enabled (including license), and configured to attach an uploaded PDF to order confirmation email

### Steps to reproduce (*)
1. Make sure Magento cronjob is **not** running
2. place two orders with different customer-data
3. execute/enable Magento cronjob
4. Check received emails and their attachments

### Expected result (*)
1. Two order-confirmation emails are sent, each containing only the data of the proper order/customer
2. Each email has only attached the configured PDF once 

### Actual result (*)
1. The confirmation email of the first order already matches the expected result
2. The confirmation email of the second order has the html-data of the first email attached, and the uploaded PDF twice

**Comment by Shinichi69** [comment]
Hi @berwa 

I’m Shin from Mageplaza and I will support you on this issue.

To resolve the issue, please download and replace the attachment with the path:
- EmailAttachments/Model/MailEvent.php
Then please try again.

Thanks so much!
[MailEvent.zip](https://github.com/mageplaza/magento-2-email-attachments/files/5456161/MailEvent.zip)

**Comment by berwa** [comment]
Hello @Shinichi69 
thank you very much for the fix.
I can confirm that it resolves our issue.

Best regards

**Comment by Shinichi69** [comment]
Hi @berwa 

Thanks for your response.

We have also updated this in the next version of the extension.
So if there is a new version, you can update normally.

If you have any other issues, please contact us again.

Thanks so much!
