### ISSUE TITLE
email-attachments Wont be attacht

### ISSUE THREAD

**Issue by kennysinkeler** [mageplaza/magento-2-email-attachments#29]
### Preconditions (*)

magento version 2.4.2
Magento 2 email ettachments Version | 4.0.1

### Steps to reproduce (*)

1. Install the plugin like as the guide 
2. Create test order

### Expected result (*)
1. A pdf attchments to the email

### Actual result (*)

1. The email don't have the Attchment

![image](https://user-images.githubusercontent.com/10799266/113873436-1c069400-97b5-11eb-9d87-abbdc1f6f9b8.png)
This are my settings, i am using also the mageplaze smtp PLugin

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza Support Team.
I have checked your extension on the local and see that it is working properly on Magento v2.4.2.
Please note that this extension attaches PDF to emails when invoices, shipments, or credit memo are sent to customers via emails.
Thank you!

**Comment by giaphn** [comment]
Closed due to no response in 7 days
