### ISSUE TITLE
Uncaught Error: Call to undefined method Magento\Framework\Mail\Message\Interceptor::createAttachment()

### ISSUE THREAD

**Issue by slavko98** [mageplaza/magento-2-email-attachments#4]
After updating Magento software from version **2.2.5** to **2.3** I encountered this error just after creating a new order (the order is created in the system however the checkout page shows an error with no message).

In the log files I can find:
`[E_ERROR] Uncaught Error: Call to undefined method Magento\Framework\Mail\Message\Interceptor::createAttachment() in (...)\vendor\mageplaza\module-email-attachments\Model\MailEvent.php:176`

From what I see the class `\Mageplaza\EmailAttachments\Model\MailEvent` uses `Magento\Framework\Mail\Message`, but this changed from `class Message extends \Zend_mail implements MessageInterface` (in Magento 2.2.5) to `class Message implements MailMessageInterface` in Magento 2.3.

So as you can see, the createAttachment method is unavailable any more.

When disabling the Mageplaza EmailAttachments module the shop works as extected (of course, without the email attachments I wanted..).

Is this a known bug or I did something wrong?

**Comment by rou9e** [comment]
Hello there !

I am pretty new to M2, so my solution might not be perfect, but I guess it could help for those who need a quick fix.

Edit **vendor/mageplaza/module-email-attachments/etc/di.xml** by adding a preference : 
<preference for="Magento\Framework\Mail\Message" type="Mageplaza\EmailAttachments\Model\Message" />

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
	<type name="Magento\Framework\Mail\TransportInterfaceFactory">
		<plugin name="mageplaza_emailattachments_transport_factory" type="Mageplaza\EmailAttachments\Mail\TransportFactory"/>
	</type>
	<preference for="Magento\Framework\Mail\Message" type="Mageplaza\EmailAttachments\Model\Message" />
</config>
```

Then create the file **vendor/mageplaza/module-email-attachments/Model/Message.php**

```
<?php

namespace Mageplaza\EmailAttachments\Model;

class Message extends \Magento\Framework\Mail\Message {

	protected $_parts = [];

	public function setBodyText($content) {
		$textPart = new \Zend\Mime\Part();
		$textPart->setContent($content)
			->setType(\Zend\Mime\Mime::TYPE_TEXT)
			->setCharset('utf-8')
		;
		$this->_parts[] = $textPart;
		return $this;
	}

	public function setBodyHtml($content) {
		$htmlPart = new \Zend\Mime\Part();
		$htmlPart->setContent($content)
			->setType(\Zend\Mime\Mime::TYPE_HTML)
			->setCharset('utf-8')
		;
		$this->_parts[] = $htmlPart;
		return $this;
	}

	public function createAttachment($content, $fileType, $disposition, $encoding, $fileName) {
		if($content === null) throw new \Exception("Param 'content' can not be null");
		if($fileType === null) $fileType = 'application/pdf';
		if($disposition === null) $disposition = \Zend\Mime\Mime::DISPOSITION_ATTACHMENT;
		if($encoding === null) $encoding = \Zend\Mime\Mime::ENCODING_BASE64;
		if($fileName === null) throw new \Exception("Param 'filename' can not be null");
		$attachmentPart = new \Zend\Mime\Part();
		$attachmentPart
			->setContent($content)
			->setType($fileType)
			->setDisposition($disposition)
			->setEncoding($encoding)
			->setFileName($fileName)
		;
		$this->_parts[] = $attachmentPart;
		$this->setPartsToBody();
		return $this;
	}

	public function setPartsToBody() {
		$mimeMessage = new \Zend\Mime\Message();
		$mimeMessage->setParts($this->_parts);
		$this->setBody($mimeMessage);
		return $this;
	}
}

```

More informations :
- https://magento.stackexchange.com/questions/252506/magento-2-3-custom-email-attachment-not-working
- https://github.com/extait-com/email-attachment/blob/master/Mail/Message.php

**Comment by Chandresh22** [comment]
Thanks @rou9e  its work.

**Comment by Chandresh22** [comment]
Hello @rou9e i implement your code and its work but other mail was send blank like newsletter subscribe.why?

**Comment by Chandresh22** [comment]
Hello @rou9e i implement your code and its work but other mail was send blank like newsletter subscribe. i found bug in
 `public function setBodyHtml($content) {
		$htmlPart = new \Zend\Mime\Part();
		$htmlPart->setContent($content)
			->setType(\Zend\Mime\Mime::TYPE_HTML)
			->setCharset('utf-8')
		;
		$this->_parts[] = $htmlPart;
		return $this;
	}`

**Comment by rou9e** [comment]
Hey there,

There was indeed a problem with my last suggestion.
My previous fix was only working on emails with attachments, but the ones without, were now blank..

You have to edit again the "**Mageplaza\EmailAttachments\Model\Message**" class.
The instruction **$this->setPartsToBody();** is missing from **setBodyText($content)** and **setBodyHtml($content)**.

See below :

```
<?php

namespace Mageplaza\EmailAttachments\Model;

class Message extends \Magento\Framework\Mail\Message {

	protected $_parts = [];

	public function setBodyText($content) {
		$textPart = new \Zend\Mime\Part();
		$textPart->setContent($content)
			->setType(\Zend\Mime\Mime::TYPE_TEXT)
			->setCharset('utf-8')
		;
		$this->_parts[] = $textPart;
		$this->setPartsToBody();
		return $this;
	}

	public function setBodyHtml($content) {
		$htmlPart = new \Zend\Mime\Part();
		$htmlPart->setContent($content)
			->setType(\Zend\Mime\Mime::TYPE_HTML)
			->setCharset('utf-8')
		;
		$this->_parts[] = $htmlPart;
		$this->setPartsToBody();
		return $this;
	}

	public function createAttachment($content, $fileType, $disposition, $encoding, $fileName) {
		if($content === null) throw new \Exception("Param 'content' can not be null");
		if($fileType === null) $fileType = 'application/pdf';
		if($disposition === null) $disposition = \Zend\Mime\Mime::DISPOSITION_ATTACHMENT;
		if($encoding === null) $encoding = \Zend\Mime\Mime::ENCODING_BASE64;
		if($fileName === null) throw new \Exception("Param 'filename' can not be null");
		$attachmentPart = new \Zend\Mime\Part();
		$attachmentPart
			->setContent($content)
			->setType($fileType)
			->setDisposition($disposition)
			->setEncoding($encoding)
			->setFileName($fileName)
		;
		$this->_parts[] = $attachmentPart;
		$this->setPartsToBody();
		return $this;
	}

	public function setPartsToBody() {
		$mimeMessage = new \Zend\Mime\Message();
		$mimeMessage->setParts($this->_parts);
		$this->setBody($mimeMessage);
		return $this;
	}
}
```

Clean cache and compile again, it works for me !
See ya ;-)

**Comment by MyoDaisy** [comment]
Also, you can download the version compatible with the magento version 2.3 in the develop branch.
