### ISSUE TITLE
After implement code other mail was blank.

### ISSUE THREAD

**Issue by Chandresh22** [mageplaza/magento-2-email-attachments#5]
other email like newsletter subscribe , forgot password are blank send.

**Comment by Tonzr** [comment]
Did you find a fix?

**Comment by Chandresh22** [comment]
Hey @Tonzr, no i am not fix it but i used https://github.com/extait-com/email-attachment

**Comment by MyoDaisy** [comment]
@Chandresh22 Could you please tell me what version of Magento are you using?  Because I tried with many Magento versions but can not reproduce the problem.

**Comment by Chandresh22** [comment]
hello @MyoDaisy  i used magento 2.3.0 so that i used https://github.com/extait-com/email-attachment module and also change look that https://github.com/extait-com/email-attachment/issues/2

**Comment by Chandresh22** [comment]
hello @MyoDaisy i will use Magento 2.3.0 and issue in preference used may be its come because other module has same preference used?

**Comment by MyoDaisy** [comment]
I have not found another solution to this problem. If there is a conflict in the future, you can create a ticket on https://mageplaza.freshdesk.com. We will help you.

**Comment by fheyer** [comment]
I can confirm this bug.

**Comment by fheyer** [comment]
Problem exists for all mail other than order, invoice, shipment, creditmemo:
Problem is that line 54 from `Mageplaza\EmailAttachments\Observer\AbstractEmail` doesn't get called:

    $this->mail->setTemplateVars($observer->getTransport());

So in turn `Mageplaza\EmailAttachments\Model\Mail::$templateVars` is `null` which makes `Mageplaza\EmailAttachments\Model\MailEvent` never call `Mageplaza\EmailAttachments\Mail\Message::setPartsToBody` (is only called if observer ran).

So the instance of `Mageplaza\EmailAttachments\Mail\Message` has values in $parts but as `setPartsToBody` never gets called `$zendMessage` never gets a message body.

So in effect all other mails don't have a body.
