### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by gewaechshaus** [mageplaza/magento-2-email-attachments#6]
Hey there,

we are using MOS 2.2.8 together with Mageplaza STMP. I also stumbled upon:
https://github.com/mageplaza/magento-2-email-attachments/issues/4
We did try to implement the fix which is mentioned in the issue, which leads to decoding problems.

We decided to implement the changes from this commit:
https://github.com/mageplaza/magento-2-email-attachments/commit/f8a117aa84520f07e88f2a69956de27311754ba4

The result is:
Fatal error: Uncaught Error: Call to undefined method Mageplaza\EmailAttachments\Mail\Message\Interceptor::createAttachment() in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php:209 Stack trace: #0 /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php(120): Mageplaza\EmailAttachments\Model\MailEvent->setTACAttachment(Object(Mageplaza\EmailAttachments\Mail\Message\Interceptor), 'default/AGB_hau...') #1 /var/www/html/vendor/mageplaza/module-email-attachments/Mail/TransportFactory.php(63): Mageplaza\EmailAttachments\Model\MailEvent->dispatch(Object(Mageplaza\EmailAttachments\Mail\Message\Interceptor)) #2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\EmailAttachments\Mail\TransportFactory->aroundCreate(Object(Magento\Framework\Mail\TransportInterfaceFactory\Interceptor), Object(Closure), Array) #3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Mail\TransportInterfaceFactory\Interceptor->Magento\F in /var/www/html/vendor/mageplaza/module-email-attachments/Model/MailEvent.php on line 209

Cheers
Jan

**Comment by Fredwak** [comment]
this problems occurs on shops higher than magento 2.3 cause magento has changed theirs mail attachment functionality

**Comment by Fredwak** [comment]
please also have a look at this link: 
https://extait.com/blog/how-to-send-email-with-attachment-in-magento-2-3/

**Comment by Fredwak** [comment]
you should download the master, instead of using composer. than you will got the working "release".

**Comment by imsamthomas** [comment]
@gewaechshaus we have fixed the issue from [SMTP](https://github.com/mageplaza/magento-2-smtp) module
